db.xii_sija_a.insertMany([
    {id: 1, nama: "Adam Fajry", mapel: "IAAS", nilai: 85},
    {id: 2, nama: "Alif Pratama", mapel: "PAAS", nilai: 87},
    {id: 3, nama: "Alifa Anindhita", mapel: "SAAS", nilai: 90},
    {id: 4, nama: "Andrian Aminudin", mapel: "SIOT", nilai: 89},
    {id: 5, nama: "Anggita Nur", mapel: "SKJ", nilai: 88},
    {id: 6, nama: "Azizah Khoirunniswa", mapel: "IAAS", nilai: 87},
    {id: 7, nama: "Damay Prasetya", mapel: "PAAS", nilai: 88},
    {id: 8, nama: "Denita Ramadani", mapel: "SAAS", nilai: 90},
    {id: 9, nama: "Diva Aulia", mapel: "SIOT", nilai: 85},
    {id: 10, nama: "Fauzan Muhammad", mapel: "SKJ", nilai: 84},
    {id: 11, nama: "Fauzan Naufal", mapel: "IAAS", nilai: 90},
    {id: 12, nama: "Firas Sabian", mapel: "PAAS", nilai: 84},
    {id: 13, nama: "Foby Rio", mapel: "SAAS", nilai: 88},
    {id: 14, nama: "Gaufa Razaky", mapel: "SIOT", nilai: 86},
    {id: 15, nama: "Hilmi Muhammad Fadlan", mapel: "SKJ", nilai: 90},
    {id: 16, nama: "Jesslyn Chiara", mapel: "IAAS", nilai: 87},
    {id: 17, nama: "Jorlando Pakpahan", mapel: "PAAS", nilai: 84},
    {id: 18, nama: "M Aprilianata", mapel: "SAAS", nilai: 87},
    {id: 19, nama: "M Rifqi", mapel: "SIOT", nilai: 87},
    {id: 20, nama: "M Rizki H", mapel: "SKJ", nilai: 86},
    {id: 21, nama: "M Aditya Resva", mapel: "IAAS", nilai: 88},
    {id: 22, nama: "M Farra", mapel: "PAAS", nilai: 89},
    {id: 23, nama: "M Luthfiandra", mapel: "SAAS", nilai: 86},
    {id: 24, nama: "M Miqdad", mapel: "SIOT", nilai: 87},
    {id: 25, nama: "M Mulki Alkarim", mapel: "SKJ", nilai: 89},
    {id: 26, nama: "M Rizky N", mapel: "IAAS", nilai: 90},
    {id: 27, nama: "M Zacky", mapel: "PAAS", nilai: 87},
    {id: 28, nama: "Muthi Munifa", mapel: "SAAS", nilai: 89},
    {id: 29, nama: "Nabila Nesya", mapel: "SIOT", nilai: 88},
    {id: 30, nama: "Randi Pratama", mapel: "SKJ", nilai: 87},
    {id: 31, nama: "Risna Putri", mapel: "IAAS", nilai: 87},
    {id: 32, nama: "Sholihoul Akbar", mapel: "PAAS", nilai: 88},
    {id: 33, nama: "Siti Maryan", mapel: "SAAS", nilai: 85},
    {id: 34, nama: "Syifa Maulidya", mapel: "SIOT", nilai: 87},
    {id: 35, nama: "Zukhruf", mapel: "SKJ", nilai: 88},
])